
name: CI/CD

on:
  # We want to run this workflow on commit to master
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # To run manually
  workflow_dispatch:

jobs:
  # Build the project and run tests (Before deploying)
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: install node_modules
        run: npm install
        
      # TODO: run tests here
      - name: run tests
        run: echo tests
      
  # Deploy to Heroku (If tests were fine)
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name:  ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
    
